#!/bin/sh

#
# @ author Ralf Habacker
#
# branch a factory package to windows:mingw

if test -z "$1"; then
    echo "$0 <package> <version>"
    exit 1
fi

target=windows:mingw
if test -n "$2"; then
    target=$2
fi

rev=$(osc log openSUSE:Factory/$1 | grep $2 | head -1 | sed 's,|.*$,,g;s,r,,g')
osc branch -r $rev openSUSE:Factory/$1 $target
