#!/bin/sh
#
# @author Ralf Habacker
#
# clone a mingw package to the other architecture e.g mingw32->mingw64 and vice versa
#
update=0
inplace=0
commit=1
if test "$1" == "--update"; then
    update=1
    shift
fi

if test "$1" == "--update-inplace"; then
    update=1
    inplace=1
    shift
fi

if test "$1" == "--no-commit"; then
    commit=0
    shift
fi

linkpac=0
linkprj=
if test "$1" == "--linkpac"; then
    linkpac=1
    shift
    linkprj=$1
    shift
fi

if [[ "$1" == "." ]]; then
    srcpkg=$(basename $PWD)
    srcprj=$(dirname $PWD | sed 's,.*/osc/,,g')
    echo $srcprj $srcpkg
elif [[ "$1" =~ "/" ]]; then
    srcprj=$(echo $1 | cut -d "/" -f 1)
    srcpkg=$(echo $1 | cut -d "/" -f 2)
else
    srcprj=$1
    srcpkg=$2
fi

if test -z "$srcprj" || test -z "$srcpkg"; then
    echo "$0 [<options>] <source project> <source package> clone package <obs-project> <obs-package>"
    echo "$0 [<options>] <source project>/<source package> clone package from <obs-path>"
    echo "$0 [<options>] .                                 clone package from current dir"
    echo "options:"
    echo "    --update"
    echo "    --update-inplace"
    echo "    --no-commit"
    echo "    --linkpac <source-project>"
    exit 1
fi

# set search patterns
srcpat=32
dstpat=64
if ! [[ $srcpkg =~ "mingw32" ]]; then
    srcpat=64
    dstpat=32
fi

srcdist=mingw$srcpat
dstdist=mingw$dstpat

# create names for destination
dstprj=$(echo $srcprj | sed "s,$srcpat,$dstpat,g")
dstpkg=$(echo $srcpkg | sed "s,mingw$srcpat,mingw$dstpat,g")

if test "$update" -ne 1; then
    # copy package to destination
    osc copypac --expand $srcprj $srcpkg $dstprj $dstpkg
    if test "$?" -ne 0; then
        echo "package exists, use --continue to override"
        exit 1
    fi
fi

# checkout package
if test "$inplace" -ne 1; then
    cd /tmp
    tmpdir=`basename $0`.$$
    mkdir -p $tmpdir
    cd $tmpdir
    if test -d "$dstprj/$dstpkg"; then
        osc update $dstprj/$dstpkg
    else
        osc co $dstprj/$dstpkg
    fi
    cd $dstprj/$dstpkg
fi

rpl="s,mingw$srcpat,mingw$dstpat,g;s,MINGW$srcpat,MINGW$dstpat,g"

# update file names
for i in $(ls *${srcdist}* 2>/dev/null); do
    echo $i
    outfile=$(echo $i | sed "$rpl")
    osc mv $i $outfile
done

# update content
for i in $(ls *${dstdist}* _multibuild 2>/dev/null); do
    echo $i
    sed -i $rpl $i
done

# check in applied changes
if test "$commit" -eq 1; then
    osc ci -m "ported to mingw$dstpat"
    if test "$?" -ne 0; then
        echo "commit failed"
        exit 1
    fi
fi

if test "$linkpac" -eq 1; then
    osc linkpac $linkprj $dstpkg $dstprj
    if test "$?" -ne 0; then
        echo "linking project failed"
        exit 1
    fi
fi

# cleanup
if test "$inplace" -ne 1; then
    rm -rf /tmp/$tmpdir
fi
