#!/bin/sh
#
# @author Ralf Habacker
#
# port native package to mingw32
#
d=$(realpath $0)
d=$(dirname $d)

(
    cd mingw32-$1
    osc mv $1.spec mingw32-$1.spec
    if test -f $1.changes; then
        osc mv $1.changes mingw32-$1.changes
    fi
    $d/patch-mingw32 $1.spec > tmp
    mv tmp mingw32-$1.spec
    echo "osc ci -m \"port to mingw32\""
)
