#!/bin/sh
#
# @author Ralf Habacker
#
# port native package to mingw32
#
d=$(realpath $0)
d=$(dirname $d)

(
    cd mingw32-$1
    if test -f $1.spec; then
        osc mv $1.spec mingw32-$1.spec
    fi
    if test -f $1.changes; then
        osc mv $1.changes mingw32-$1.changes
    fi
    if test -f $1-rpmlintrc; then
        osc mv $1-rpmlintrc mingw32-$1-rpmlintrc
    fi
    $d/patch-mingw32 mingw32-$1.spec > tmp
    mv tmp mingw32-$1.spec
    echo "osc ci -m \"port to mingw32\""
)
