#!/bin/sh
#
# @author Ralf Habacker
#
# port native package to mingw32|64
#
d=$(realpath $0)
d=$(dirname $d)

if test "$1" == "-r"; then
    shift
    options="-r $1"
    shift
fi

srcprj=$1
srcpkg=$2
cdir=0

indstprj=0
indstpkg=0
if [[ "$3" == "." ]]; then
    dstprj=$(osc meta prj | grep "^<project" | sed 's,^.*=",,g;s,".*$,,g')
    if test -n "$dstprj"; then
        indstprj=1
    else
        echo "not in destination project"
        exit 1
    fi
    # check if in destination package
    dstpkg=$(osc meta pkg | grep '<package' | sed 's,.*name=",,g;s,".*$,,g')
    if test -n "$dstpkg"; then
        indstpkg=1
    fi
else
    dstprj=$3
fi
if [[ $dstprj =~ "32" ]]; then
    dstpat=mingw32
else
    dstpat=mingw64
fi
dstpkg=$dstpat-$srcpkg
echo $dstprj $dstpkg

if test -z "$srcprj" || test -z "$srcpkg"; then
    echo "$0 [<options>] <source project> <source package> <destination project>     port native package from <source-project> <source-package> to <destination project>"
    echo "$0 [<options>] <source project> <source package> .                         port native package from <source-project> <source-package> to osc project or package in current dir"
    exit 1
fi

(
    # check is destination package exists
    osc meta pkg $dstprj $dstpkg > /dev/null 2>&1
    if test $? -eq 0; then
        dstpkgexits=1
    else
        osc copypac -e $srcprj $srcpkg $dstprj $dstpkg
        if test $? -ne 0; then
            exit 2
        fi
    fi

    # in destination project
    if test $indstprj -eq 1; then
        osc co $dstpkg
        if test $? -ne 0; then
            exit 2
        fi
        echo "Entering $dstpkg"
        cd $dstpkg
    elif test $indstpkg -ne 1; then
        cd ~/osc
        osc co $dstprj $dstpkg
        if test $? -ne 0; then
            exit 3
        fi
        echo "Entering $dstprj/$dstpkg"
        cd $dstprj/$dstpkg
    fi
    # port files
    if test -f $srcpkg.spec; then
        osc mv $srcpkg.spec $dstpkg.spec
        $d/patch-$dstpat $dstpkg.spec > tmp
        mv tmp $dstpkg.spec
    fi
    if test -f $srcpkg.changes; then
        osc mv $srcpkg.changes $dstpkg.changes
    fi
    if test -f $srcpkg-rpmlintrc; then
        osc mv $srcpkg-rpmlintrc $dstpkg-rpmlintrc
    fi
    echo "Run the following commit to submit"
    echo "osc ci -m \"port to $dstpat\""
)
